"""auto update

Revision ID: 64753ed93f3b
Revises: 7dce47ff4b78
Create Date: 2026-02-12 01:37:43.083508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64753ed93f3b'
down_revision: Union[str, Sequence[str], None] = '7dce47ff4b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('suggested_points', sa.Integer(), nullable=False),
    sa.Column('approved_points', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('admin_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_activities_id'), 'community_activities', ['id'], unique=False)
    op.add_column('user_profiles', sa.Column('badges', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'badges')
    op.drop_index(op.f('ix_community_activities_id'), table_name='community_activities')
    op.drop_table('community_activities')
    # ### end Alembic commands ###