"""auto update

Revision ID: ef8ecc782462
Revises: 64753ed93f3b
Create Date: 2026-02-14 22:54:34.533371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8ecc782462'
down_revision: Union[str, Sequence[str], None] = '64753ed93f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('role', sa.String(), server_default='user', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'role')
    # ### end Alembic commands ###